language: node_js
dist: trusty
before_script:
- bin/setup
sudo: required
before_install:
- export DISPLAY=:99.0
- export TZ=Europe/Zurich
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- bin/check
- bin/check-server-start
cache:
  directories:
  - node_modules
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - zsh
    - g++-4.8
    - google-chrome-stable
after_failure:
  - cat /home/travis/build/renuo/ngx-renuo-upload/server_prod.log
